### ISSUE TITLE
Simpson layout still has a css file

### ISSUE THREAD

**Issue by jenlampton** [biolithic/backdroplayouts#1]
I'm not sure we want a simpson / bartik layout, but in case we do here's what we need to do to clean it up:
- remove the css file
- sandardize icon style
- standardize region names
- remove extraneous css classes. 

PR attached does all these things.

**Comment by biolithic** [comment]
yea, I'm lacking for time so these are some things we will have to do.

**Comment by jenlampton** [comment]
Is it okay if I turn this repo into a PR?
