### ISSUE TITLE
Fewer div tags / remove the ability to add stripes everywhere

### ISSUE THREAD

**Issue by jenlampton** [biolithic/backdroplayouts#30]
I can see that @wesruv added more wrapper and container tags for lots of the elements on the page so that themes could have the option of creating full-width stripes. However, I keep looking at the code with distaste. There are just so many div tags this way - and for most sites (80%?) the full-width stripes are likely to be 1) header 2) footer 3) the stuff in the middle.

I'm tempted to leave only those three sets of wrapper & inner-wrappers, and if people want more stripes in their themes, they can override the template files in their themes to match.

I don't like the idea of adding a bunch of cruft into core "just in case".

**Comment by biolithic** [comment]
@jenlampton  I've already created duplicates of the core layouts in zurb 6 framework with less markup which I will leave in contrib.  I feel that people can choose (all the options/divs) or (not so many options/divs).  So, whatever you choose, I'll just put the opposite in contrib.

**Comment by jenlampton** [comment]
That sounds great @biolithic :)

**Comment by jenlampton** [comment]
Okay, I just pushed up a version with fewer divs around title, messages, tabs, and other regions.

**Comment by wesruv** [comment]
Better late than never, I agree with the contrib approach. I was thinking the default would be more verbose and support more designs, and contrib/specific themes can axe the extra markup if they know they don't want it.
