### ISSUE TITLE
Make all layouts content-first using push and pull classes

### ISSUE THREAD

**Issue by jenlampton** [biolithic/backdroplayouts#36]
Just creating this ticket so we can see what is left to do before merge :)

**Comment by biolithic** [comment]
This is implemented on local and once merging is done this afternoon will be done.

**Comment by jenlampton** [comment]
Can you update the current PR, maybe?
- -
  Please excuse brevity and typos. Message typed with my thumbs from an Open
  Source OS.

**Comment by biolithic** [comment]
My mice are not working or need batteries so I'm out to get some now, sorry
for delay.

**Comment by biolithic** [comment]
done in https://github.com/biolithic/backdroplayouts/commit/8b2a7103f026d226d48e0b2dfbd5c3c513f07188
