### ISSUE TITLE
Ensure all first sidebar regions are named `sidebar` and not `sidebar1`

### ISSUE THREAD

**Issue by jenlampton** [biolithic/backdroplayouts#37]
This is so that when moving from a layout with one sidebar to one that has two the content will automatically map to the first sidebar.  I noticed that these names keep getting changed, if you copy/paste templates instead of pulling, please be careful that these don't get overwritten again :)

**Comment by biolithic** [comment]
OK,
sidebar1, third1, customregion1 are more consistent but sidebar, sidebar2
will upgrade better from 1.3 so it's your choice

**Comment by jenlampton** [comment]
for elements like thirds and quarters there are always 3 or 4 of them. With sidebars sometimes there is one and sometimes there is two.
